CREATE TABLE PAISES(
    id number PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE INFECCIONES(
    id number PRIMARY KEY,
    id_pais number not null,
    fecha date not null,
    nuevas_i integer not null,
);

CREATE TABLE INFECCIONES_ACUMULADAS(
    id number PRIMARY KEY,
    pais VARCHAR2(100) not null,
    fecha date not null,
    nuevas_i integer not null,
    cantidad_i integer,
);

ALTER TABLE P_I ADD CONSTRAINT PAISES_INFECCIONES_FK FOREIGN KEY (id_pais) REFERENCES PAISES(id);

declare
    cursor ITERADOR_INFECTADOS is
        select * from INFECCIONES;
    REGISTRO_INFECCIONES INFECCIONES%rowtype;
    ACUMULADO INTEGER;
BEGIN
    ACUMULADO := 0;
    OPEN ITERADOR_INFECTADOS;
    FETCH ITERADOR_INFECTADOS INTO REGISTRO_INFECCIONES;
    WHILE ITERADOR_INFECTADOS%FOUND
        LOOP
        ACUMULADO := ACUMULADO + REGISTRO_INFECCIONES.nuevas_i;
        INSERT INTO INFECCIONES_ACUMULADAS 
            VALUES(REGISTRO_INFECCIONES.id,SELECT p.nombre FROM PAISES p WHERE REGISTRO_INFECCIONES.id_pais = p.id,
                    REGISTRO_INFECCIONES.fecha,REGISTRO_INFECCIONES.nuevas_i,ACUMULADO);
        FETCH ITERADOR_INFECTADOS INTO REGISTRO_INFECCIONES;
        END LOOP;
CLOSE ITERADOR_INFECTADOS;
